import CalculateFreight from "./application/CalculateFreight";
import Checkout from "./application/Checkout";
import CLIController from "./infrastructure/cli/CLIController";
import CLIHandler from "./infrastructure/cli/CLIHandler";
import CLIHandlerNode from "./infrastructure/cli/CLIHandlerNode";
import CouponDataDatabase from "./infrastructure/data/CouponDataDatabase";
import OrderDataDatabase from "./infrastructure/data/OrderDataDatabase";
import ProductDataDatabase from "./infrastructure/data/ProductDataDatabase";
import ZipcodeDataDatabase from "./infrastructure/data/ZipcodeDataDatabase";
import PgPromiseConnection from "./infrastructure/database/PgPromiseConnection";

const connection = new PgPromiseConnection();
const productData = new ProductDataDatabase(connection);
const couponData = new CouponDataDatabase(connection);
const orderData = new OrderDataDatabase(connection);
const zipcodeData = new ZipcodeDataDatabase(connection);
const calculateFreight = new CalculateFreight(productData, zipcodeData);
const checkout = new Checkout(productData, couponData, orderData, calculateFreight);
const handler = new CLIHandlerNode();
new CLIController(handler, checkout);